name: CI

on:
  push:
    branches: [main, dev, dev-bash-to-python]
  pull_request:
    branches: [main, dev, dev-bash-to-python]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm
      - name: Install dependencies
        run: pdm install -G lint -G test
      - name: Ruff (lint)
        run: pdm run lint-ruff
      # - name: Black (check)
        # run: pdm run lint-black
      - name: Pylint
        run: pdm run lint-pylint
      # - name: Pydocstyle
        # run: pdm run pydocstyle --convention=google docker_ctp
      - name: Run tests
        run: pdm run pytest --cov=docker_ctp --cov-report=term-missing
